//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ProjectFactBujet
    {
        public int id { get; set; }
        public string period { get; set; }
        public double data { get; set; }
        public string devision { get; set; }
        public string order { get; set; }
    }
}
