//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_WorkerResultThisPeriod
    {
        public int id { get; set; }
        public string id_AspNetUsers { get; set; }
        public double fOrdersAndN { get; set; }
        public double fManagers { get; set; }
        public double fManagerOrders { get; set; }
        public double KPI { get; set; }
        public double teach { get; set; }
        public double optimizationTasks { get; set; }
        public double qualityBonus { get; set; }
        public double timeBonus { get; set; }
        public double nk { get; set; }
        public double fBonusRemaining { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
