//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO2_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMO2_Order()
        {
            this.CMO2_Position = new HashSet<CMO2_Position>();
        }
    
        public int id { get; set; }
        public string id_AspNetUsers_Create { get; set; }
        public System.DateTime dateTimeCreate { get; set; }
        public bool workIn { get; set; }
        public Nullable<System.DateTime> workDateTime { get; set; }
        public bool workComplitet { get; set; }
        public double workCost { get; set; }
        public bool manufIn { get; set; }
        public Nullable<System.DateTime> manufDate { get; set; }
        public bool manufComplited { get; set; }
        public double manufCost { get; set; }
        public bool finIn { get; set; }
        public Nullable<System.DateTime> finDate { get; set; }
        public bool finComplited { get; set; }
        public double finCost { get; set; }
        public string folder { get; set; }
        public bool reOrder { get; set; }
        public Nullable<int> id_CMO_Company { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CMO_Company CMO_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMO2_Position> CMO2_Position { get; set; }
    }
}
