//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMO_Order()
        {
            this.CMO_FileOrder = new HashSet<CMO_FileOrder>();
            this.CMO_Mail = new HashSet<CMO_Mail>();
            this.CMO_PositionOrder = new HashSet<CMO_PositionOrder>();
            this.CMO_Tender = new HashSet<CMO_Tender>();
        }
    
        public int id { get; set; }
        public System.DateTime dateCreate { get; set; }
        public string userCreate { get; set; }
        public bool firstTenderStart { get; set; }
        public Nullable<System.DateTime> datetimeFirstTenderFinish { get; set; }
        public string userFirstTenderStart { get; set; }
        public string folder { get; set; }
        public double idTime { get; set; }
        public Nullable<System.DateTime> datetimeSecondTenderFinish { get; set; }
        public Nullable<System.DateTime> datetimeWinTenderFinish { get; set; }
        public Nullable<int> companyWin { get; set; }
        public Nullable<System.DateTime> dateCloseOrder { get; set; }
    
        public virtual CMO_Company CMO_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMO_FileOrder> CMO_FileOrder { get; set; }
        public virtual CMO_HoureTender CMO_HoureTender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMO_Mail> CMO_Mail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMO_PositionOrder> CMO_PositionOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMO_Tender> CMO_Tender { get; set; }
    }
}
