//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_Tender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMO_Tender()
        {
            this.CMO_UploadResult = new HashSet<CMO_UploadResult>();
        }
    
        public int id { get; set; }
        public int id_CMO_Order { get; set; }
        public int id_CMO_TypeTask { get; set; }
        public System.DateTime finishPlanClose { get; set; }
        public bool close { get; set; }
        public Nullable<System.DateTime> closeDateTime { get; set; }
        public string userClose { get; set; }
    
        public virtual CMO_Order CMO_Order { get; set; }
        public virtual CMO_TypeTask CMO_TypeTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMO_UploadResult> CMO_UploadResult { get; set; }
    }
}
