//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_Mail
    {
        public int id { get; set; }
        public int id_CMO_Order { get; set; }
        public int id_CMO_TypeTask { get; set; }
        public System.DateTime dateTimePush { get; set; }
        public string email { get; set; }
        public string body { get; set; }
        public string listFileName { get; set; }
    
        public virtual CMO_Order CMO_Order { get; set; }
        public virtual CMO_TypeTask CMO_TypeTask { get; set; }
    }
}
