//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_FileOrder
    {
        public int id { get; set; }
        public int id_CMO_Order { get; set; }
        public string filname { get; set; }
    
        public virtual CMO_Order CMO_Order { get; set; }
    }
}
