//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_TN
    {
        public int @int { get; set; }
        public int id_DebitTask { get; set; }
        public string numberTN { get; set; }
        public System.DateTime dateTN { get; set; }
        public string numberSF { get; set; }
        public System.DateTime dateSF { get; set; }
        public double Summa { get; set; }
        public Nullable<int> id_PZ_PlanZakaz { get; set; }
    }
}
