//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBP_ProjectTasks
    {
        public int id { get; set; }
        public Nullable<double> basicDuration { get; set; }
        public Nullable<System.DateTime> basicStart { get; set; }
        public Nullable<System.DateTime> basicFinish { get; set; }
        public Nullable<double> basicWork { get; set; }
        public double duration { get; set; }
        public double remainingDuration { get; set; }
        public double factDuration { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime finish { get; set; }
        public double work { get; set; }
        public double remainingWork { get; set; }
        public double factWork { get; set; }
        public double percentWorkComplited { get; set; }
        public double percentComplited { get; set; }
        public double percentPhisicalComplited { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public bool isCritical { get; set; }
        public int priority { get; set; }
        public Nullable<double> NK { get; set; }
        public Nullable<int> id_WBS { get; set; }
        public int id_DashboardBP_ProjectList { get; set; }
        public System.Guid taskUID { get; set; }
        public string id_AspNetUsers { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DashboardBP_ProjectList DashboardBP_ProjectList { get; set; }
        public virtual WBS WBS { get; set; }
    }
}
