//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTV_DataForProjectPortfolio
    {
        public int id { get; set; }
        public string orderNumber { get; set; }
        public int tcpm { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime to { get; set; }
        public System.DateTime dataOtgruzkiBP { get; set; }
    }
}
