//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardKOKBHss
    {
        public string Quart { get; set; }
        public double KBM { get; set; }
        public double KBE { get; set; }
        public int id { get; set; }
        public double KBMR { get; set; }
        public double KBER { get; set; }
    }
}
