//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBP_ProjectList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashboardBP_ProjectList()
        {
            this.DashboardBP_TasksList = new HashSet<DashboardBP_TasksList>();
        }
    
        public int id { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public int id_DashboardBP_State { get; set; }
        public System.DateTime contractDate { get; set; }
        public System.DateTime planDateComplited { get; set; }
        public System.DateTime planDateStart { get; set; }
        public int planDuration { get; set; }
        public int planProjectPercentCompleted { get; set; }
    
        public virtual DashboardBP_State DashboardBP_State { get; set; }
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardBP_TasksList> DashboardBP_TasksList { get; set; }
    }
}
