//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardKOMP3
    {
        public string period { get; set; }
        public string ciliricalName { get; set; }
        public string devisionName { get; set; }
        public double k { get; set; }
        public double plan { get; set; }
        public double plan10 { get; set; }
        public double plan20 { get; set; }
        public double plan30 { get; set; }
        public double normHoure { get; set; }
        public double normHoureFact { get; set; }
        public int id { get; set; }
    }
}
