//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBP_State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashboardBP_State()
        {
            this.DashboardBP_HSSPO = new HashSet<DashboardBP_HSSPO>();
            this.DashboardBP_ProjectList = new HashSet<DashboardBP_ProjectList>();
            this.DashboardHSSPlan = new HashSet<DashboardHSSPlan>();
            this.DashboardRatePlan = new HashSet<DashboardRatePlan>();
            this.DashboardRemaining = new HashSet<DashboardRemaining>();
        }
    
        public int id { get; set; }
        public System.DateTime datetime { get; set; }
        public short numberWeek { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardBP_HSSPO> DashboardBP_HSSPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardBP_ProjectList> DashboardBP_ProjectList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardHSSPlan> DashboardHSSPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardRatePlan> DashboardRatePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardRemaining> DashboardRemaining { get; set; }
    }
}
