//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_DataReportOprih
    {
        public int id { get; set; }
        public int id_DebitWork { get; set; }
        public int id_Debit_PeriodReportOprih { get; set; }
        public System.DateTime dateOprihPlanFact { get; set; }
        public bool oprihClose { get; set; }
        public string description { get; set; }
        public string numberSF { get; set; }
        public string reclamation { get; set; }
        public Nullable<System.DateTime> reclamationOpen { get; set; }
        public Nullable<System.DateTime> reclamationClose { get; set; }
        public double costWithHDS { get; set; }
        public double costNotNDS { get; set; }
        public double costNDS { get; set; }
        public int id_Debit_PostingOnType { get; set; }
        public int id_Debit_PostingOffType { get; set; }
    
        public virtual Debit_PeriodReportOprih Debit_PeriodReportOprih { get; set; }
        public virtual Debit_PostingOffType Debit_PostingOffType { get; set; }
        public virtual Debit_PostingOnType Debit_PostingOnType { get; set; }
        public virtual Debit_WorkBit Debit_WorkBit { get; set; }
    }
}
