//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_Platform
    {
        public int id { get; set; }
        public Nullable<int> id_PlanZakaz { get; set; }
        public Nullable<int> massa { get; set; }
        public Nullable<int> countPlatform { get; set; }
        public string numPlatform { get; set; }
        public string numPlomb { get; set; }
        public string gabar { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
