//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_SmallReport
    {
        public int id { get; set; }
        public int id_TaskForPZ { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime datePlanFirst { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
        public bool close { get; set; }
        public int id_PlanZakaz { get; set; }
        public System.DateTime datePlan { get; set; }
        public string taskName { get; set; }
        public Nullable<int> Predecessors { get; set; }
        public int PlanZakaz { get; set; }
    }
}
