//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSSPO
    {
        public string PK { get; set; }
        public string OrderPZ { get; set; }
        public Nullable<System.Guid> TaskUID { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> TimeByDay { get; set; }
        public Nullable<decimal> AssignmentWork { get; set; }
        public Nullable<decimal> CountPO { get; set; }
        public Nullable<double> RatePlan { get; set; }
        public Nullable<double> SSMPlan { get; set; }
        public Nullable<double> SSMFact { get; set; }
        public Nullable<double> SSRPlan { get; set; }
        public Nullable<double> ik { get; set; }
        public Nullable<double> ppk { get; set; }
        public Nullable<double> pi { get; set; }
        public Nullable<double> nop { get; set; }
        public Nullable<double> RateHoure { get; set; }
        public Nullable<double> ssmHoure { get; set; }
        public Nullable<double> ssmFactHoure { get; set; }
        public Nullable<double> ssrHoure { get; set; }
        public Nullable<double> ikHoure { get; set; }
        public Nullable<double> ppkHoure { get; set; }
        public Nullable<double> piHoure { get; set; }
        public Nullable<double> nopHoure { get; set; }
        public Nullable<double> xRate { get; set; }
        public Nullable<double> xSSM { get; set; }
        public Nullable<double> xSSMFact { get; set; }
        public Nullable<double> xSSR { get; set; }
        public Nullable<double> xIK { get; set; }
        public Nullable<double> xPPK { get; set; }
        public Nullable<double> xPI { get; set; }
        public Nullable<double> xNOP { get; set; }
    }
}
