//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanVerificationItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanVerificationItems()
        {
            this.PlanVerificationItemsLog = new HashSet<PlanVerificationItemsLog>();
        }
    
        public int id { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public bool @fixed { get; set; }
        public bool fixetFirstDate { get; set; }
        public Nullable<System.DateTime> planDate { get; set; }
        public string planDescription { get; set; }
        public Nullable<System.DateTime> factDate { get; set; }
        public string factDescription { get; set; }
        public Nullable<System.DateTime> appDate { get; set; }
        public string appDescription { get; set; }
        public Nullable<System.DateTime> verificationDateInPrj { get; set; }
        public Nullable<System.DateTime> fixedDateForKO { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanVerificationItemsLog> PlanVerificationItemsLog { get; set; }
    }
}
