//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMSP_EpmProject_UserView
    {
        public System.Guid ProjectUID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectFinishDate { get; set; }
        public Nullable<decimal> ProjectDurationVariance { get; set; }
        public Nullable<decimal> ProjectStartVariance { get; set; }
        public Nullable<decimal> ProjectFinishVariance { get; set; }
        public Nullable<decimal> ProjectDuration { get; set; }
        public Nullable<decimal> ProjectActualDuration { get; set; }
        public Nullable<System.DateTime> ProjectActualStartDate { get; set; }
        public Nullable<System.DateTime> ProjectActualFinishDate { get; set; }
        public Nullable<short> ProjectPercentCompleted { get; set; }
        public Nullable<short> ProjectPercentWorkCompleted { get; set; }
        public Nullable<decimal> ProjectWorkVariance { get; set; }
    }
}
