//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectServer_UpdateTasks
    {
        public int id { get; set; }
        public Nullable<double> nk { get; set; }
        public Nullable<double> np { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<double> percentComplited { get; set; }
        public System.Guid projectUID { get; set; }
        public System.Guid taskUID { get; set; }
        public bool uploadData { get; set; }
    }
}
