//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectServer_CreateTasks
    {
        public int id { get; set; }
        public System.Guid ProjectUID { get; set; }
        public string TaskName { get; set; }
        public int Work { get; set; }
        public string Resource { get; set; }
        public Nullable<int> Devision { get; set; }
        public bool update { get; set; }
    }
}
