//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PZ_PlanZakaz
    {
        public int Id { get; set; }
        public int PlanZakaz { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string MTR { get; set; }
        public string Name { get; set; }
        public string OL { get; set; }
        public int Zapros { get; set; }
        public System.DateTime DateSupply { get; set; }
        public System.DateTime DateShipping { get; set; }
        public double Cost { get; set; }
        public string Description { get; set; }
        public int ProductType { get; set; }
        public int Dostavka { get; set; }
        public string Manager { get; set; }
        public int Client { get; set; }
        public string Gruzopoluchatel { get; set; }
        public string PostAdresGruzopoluchatel { get; set; }
        public string INNGruzopoluchatel { get; set; }
        public string OKPOGruzopoluchatelya { get; set; }
        public string KodGruzopoluchatela { get; set; }
        public string StantionGruzopoluchatel { get; set; }
        public string KodStanciiGruzopoluchatelya { get; set; }
        public string OsobieOtmetkiGruzopoluchatelya { get; set; }
        public string DescriptionGruzopoluchatel { get; set; }
        public string Folder { get; set; }
        public string PowerST { get; set; }
        public string VN_NN { get; set; }
        public string Modul { get; set; }
        public string timeContract { get; set; }
        public Nullable<System.DateTime> timeContractDate { get; set; }
        public string timeArr { get; set; }
        public Nullable<System.DateTime> timeArrDate { get; set; }
        public int id_PZ_FIO { get; set; }
        public string numZakupki { get; set; }
        public string numLota { get; set; }
        public System.DateTime dataOtgruzkiBP { get; set; }
        public Nullable<System.Guid> ProjectUID { get; set; }
        public string nameTU { get; set; }
        public int TypeShip { get; set; }
        public Nullable<System.DateTime> criticalDateShip { get; set; }
        public int id_PZ_OperatorDogovora { get; set; }
        public double costPNR { get; set; }
        public double costSMR { get; set; }
        public string nomenklaturNumber { get; set; }
    }
}
