//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PZ_TEO
    {
        public int id { get; set; }
        public int Id_PlanZakaz { get; set; }
        public int Currency { get; set; }
        public double Rate { get; set; }
        public double SSM { get; set; }
        public double SSR { get; set; }
        public double IzdKom { get; set; }
        public double IzdPPKredit { get; set; }
        public double PI { get; set; }
        public double NOP { get; set; }
        public double KI_S { get; set; }
        public double KI_prochee { get; set; }
        public double OtpuskChena { get; set; }
        public Nullable<double> KursValuti { get; set; }
        public Nullable<double> NDS { get; set; }
        public Nullable<double> SSRFact { get; set; }
        public Nullable<double> percentYear { get; set; }
        public Nullable<double> percentPI { get; set; }
        public Nullable<double> durationBeforePay { get; set; }
    
        public virtual PZ_Currency PZ_Currency { get; set; }
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
