//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation_TechnicalAdviceProtocolPosition
    {
        public int id { get; set; }
        public int id_Reclamation_TechnicalAdvice { get; set; }
        public int id_Reclamation_TechnicalAdviceProtocol { get; set; }
    
        public virtual Reclamation_TechnicalAdvice Reclamation_TechnicalAdvice { get; set; }
        public virtual Reclamation_TechnicalAdviceProtocol Reclamation_TechnicalAdviceProtocol { get; set; }
    }
}
