//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_QuestionData
    {
        public int id { get; set; }
        public int id_RKD_Question { get; set; }
        public System.DateTime dateUpload { get; set; }
        public string userUpload { get; set; }
        public string textData { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual RKD_Question RKD_Question { get; set; }
    }
}
