//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_Despatching
    {
        public int id { get; set; }
        public Nullable<int> id_RKD_Order { get; set; }
        public Nullable<System.DateTime> dateEvent { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> dateTaskFinishDate { get; set; }
        public string id_AspNetUsers { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual RKD_Order RKD_Order { get; set; }
    }
}
