//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_PostList
    {
        public int id { get; set; }
        public string email { get; set; }
        public int id_TypeRKD_Mail_Version { get; set; }
    
        public virtual TypeRKD_Mail_Version TypeRKD_Mail_Version { get; set; }
    }
}
