//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCells
    {
        public int id { get; set; }
        public int sectionIdStart { get; set; }
        public string name1 { get; set; }
        public int sectionIdFinish { get; set; }
        public string name2 { get; set; }
        public double distance { get; set; }
    }
}
