//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRemarksCauses
    {
        public int id { get; set; }
        public int id_ServiceRemarksCause { get; set; }
        public int id_ServiceRemarks { get; set; }
    
        public virtual ServiceRemarks ServiceRemarks { get; set; }
        public virtual ServiceRemarksCause ServiceRemarksCause { get; set; }
    }
}
