//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTEO
    {
        public int id { get; set; }
        public int planZakaz { get; set; }
        public System.DateTime dateShip { get; set; }
        public double viruchka { get; set; }
        public double oChena { get; set; }
        public double izKom { get; set; }
        public double percKredit { get; set; }
        public double ssm { get; set; }
        public double fssm { get; set; }
        public double sspo { get; set; }
        public double fsspo { get; set; }
        public double curency { get; set; }
        public double pi { get; set; }
        public string valut { get; set; }
        public System.DateTime dateOpen { get; set; }
    }
}
