//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManpowerKOUsers.ContextExport1c
{
    using System;
    using System.Collections.Generic;
    
    public partial class planZakaz
    {
        public int id { get; set; }
        public string Zakaz { get; set; }
        public Nullable<System.DateTime> Otgruzka { get; set; }
        public Nullable<System.DateTime> Otkr { get; set; }
        public Nullable<int> SSmat { get; set; }
        public Nullable<int> bujetIspoln { get; set; }
        public Nullable<double> bujetProizv { get; set; }
        public Nullable<double> bujetRezerv { get; set; }
        public Nullable<double> obespechenost { get; set; }
        public Nullable<double> SSfact1 { get; set; }
        public Nullable<bool> bitVipusk { get; set; }
        public Nullable<bool> bitRKD { get; set; }
        public Nullable<System.DateTime> startUSS { get; set; }
        public Nullable<System.DateTime> startEU { get; set; }
        public string OboznacIzdelia { get; set; }
        public string NaimenovanieIzdelia { get; set; }
        public Nullable<bool> mir { get; set; }
        public Nullable<double> procentIzmeneniyStoimDeficita { get; set; }
        public Nullable<System.DateTime> dataRezresheniyaProizvodstva { get; set; }
        public Nullable<bool> PVProvedena { get; set; }
        public Nullable<bool> OVProvedena { get; set; }
        public Nullable<double> SSSDI { get; set; }
        public Nullable<double> SSfact { get; set; }
    }
}
